---
# tasks file for mqtt_container
- name: Download the docker container image
  docker_image:
    name: "{{ item.image }}"
    source: pull
  become: yes
  when: ansible_facts['os_family'] == "Debian"
  loop: "{{ containers }}"

- name: Download the podman container image
  podman_image:
    name: "{{ item.image }}"
  become: yes
  when: ansible_facts['os_family'] == "RedHat"
  loop: "{{ containers }}"


- name: Copy the docker start service file for launch
  template:
    src: "docker.{{ item.name }}.service.j2"
    dest: "/etc/systemd/system/{{ item.name }}.service"
    mode: "0644"
  become: true
  notify: daemon_reload
  when: ansible_facts['os_family'] == "Debian"
  loop: "{{ containers }}"

- name: Inspect if the docker container is running already
  shell: "docker ps -a"
  become: true
  tags: shell
  register: docker_status
  when: ansible_facts['os_family'] == "Debian"

- name: Create a docker container of Mosquitto first
  shell: "docker run -d -p {{ item.ports | join(' -p ') }} --name {{ item.name }} {{ item.image }} && docker stop {{ item.name }}"
  become: true
  changed_when: false
  loop: "{{ containers}}"
  when: ansible_facts['os_family'] == "Debian" and docker_status.stdout.find('mosquitto') == -1 and docker_status.stdout.find('plantuml') == -1

- name: Inspect if the podman container is running already
  shell: "podman ps -a"
  become: true
  tags: shell
  register: container_status
  changed_when: false
  when: ansible_facts['os_family'] == "RedHat"

- name: Create a podman container of Mosquitto first
  shell: "podman run -d -p {{ item.ports| join(' -p ') }} --name {{ item.name }} {{ item.image }}  && podman stop {{ item.name }}"
  become: true
  changed_when: false
  loop: "{{ containers }}"
  when: ansible_facts['os_family'] == "RedHat" and container_status.stdout.find('mosquitto') == -1 and container_status.stdout.find('plantuml') == -1

- name: Copy the file into the appropriate location
  template:
    src: "podman.service.j2"
    dest: "/etc/systemd/system/{{ item.name }}.service"
    mode: "0644"
  become: yes
  when: ansible_facts['os_family'] == "RedHat" 
  notify: daemon_reload
  loop: "{{ containers }}"

- name: FLush Handlers
  meta: flush_handlers

- name: Start the service of container
  service: 
    name: "{{ item.name }}"
    state: started
    enabled: true
  become: true
  loop: "{{ containers }}"

- name: Adding the firewall rule for Redhat
  firewalld:
    port: "{{  item }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  when: ansible_facts['os_family'] == "RedHat"
  become: true
  loop:
      - 1883
      - 80

- name: Firewall rule for Ubuntu System
  ufw:
    port: "{{ item }}"
    proto: tcp
    rule: allow
  when: ansible_facts['os_family'] == "Debian"
  become: true
  loop:
      - 1883
      - 80

